spring:
  application:
    name: concert-server

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommerce
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19095


